### ISSUE TITLE
removing SSH keys from the installer doesn't work

### ISSUE THREAD

**Issue by nbeernink** [atomia/puppetmaster-gui#1]
On http://hostname:3000/keys you can add SSH keys. I added a key but thought the ssh-rsa part wasn't needed. The atomia page accepted my input anyway. (no validation?) 

I tried to remove the bad key by clicking the remove button but this redirects to the add key page.

**Comment by stefanmortensen** [comment]
Hi,
Thanks for the issue report. You are correct this is a feature has been overlooked. I will assign the issue to me and add this.

For now the only way to do it would be directly through the database.
