### ISSUE TITLE
Shared servers for services

### ISSUE THREAD

**Issue by fallenpeace** [atomia/puppetmaster-gui#25]
Maybe this isn't the place to ask this?

But from looking at the gui installer it seems that each services gets put on a separate server.

Is there a way to install multiple services on one server?

Odd example: DNS server on the same server EMAIL is served from?

**Comment by stefanmortensen** [comment]
Hi,
Good question :). There is not yet support for combining services on one server through the GUI. However it makes perfect sense and is technically possible to merge alot of the services in order to provision smaller environments.

This is already planned and I'll keep this issue open as a "todo" in order to get this implemented. I'd like to see both pre made templates for test/evaluation environments where a minimum number of servers are required for a complete environment. As well as the possibility to combine some of the services like in your example.

**Comment by fallenpeace** [comment]
Awesome glad to see this planned! 30-ish servers is alot of servers to provision, so being able to deploy Atomia on a minimal amount of servers would be ideal for someone starting up. 👍  +1 on premade templates.

**Comment by stefanmortensen** [comment]
It's possible yet a bit cumbersome to install manually by injecting the variables into hiera through yaml config files. If you are keen to get started there is a description how to do this in https://github.com/atomia/puppet-atomia/tree/stable.

**Comment by fallenpeace** [comment]
@stefanmortensen, thanks for the link! I'll try to work my way through this, all though I'm relatively new to understanding things like puppet.

Is there any resource that outlines the minimal requirements for a shared hosting environment (no vps, no cloud)?

**Comment by stefanmortensen** [comment]
@fallenpeace, I can probably have support for mixing roles on the same server by next week. I don't know your time schedule, maybe it makes more sense to wait for this? Deploying manually is kind of prone to errors and might be a struggle without previous Puppet knowledge.

Regarding minimal requirements for testing/development we run all Atomia Windows applications with database and Active Directory on a single server and provisions resource servers as needed. If you are going to use the environment for anything but testing/development I suggest at least the following virtual machines:

Atomia applications/agents
1 Active Directory
1 Windows server for Atomia applications
1 Ubuntu server for Atomia database (PostgreSQL)
2 Ubuntu servers for the different agents/services

Customer shared hosting 
1 Ubuntu Load balancer (Haproxy)
1 Ubuntu web server + ftp
1 Ubuntu mail server
1 of each required customer databse server (MySQL, PostgreSQL, MSSQL)

**Comment by fallenpeace** [comment]
@stefanmortensen Honestly, you're awesome. 👍

**Comment by stefanmortensen** [comment]
@fallenpeace I have now made it possible to assign multiple roles to a single server (up to 5 roles). In addition to #34 you also need the latest puppet module https://github.com/atomia/puppet-atomia/pull/122. 

This is not final and I would like to improve this by having pre made templates with merged roles however as this was a quick solution to start allowing mering of roles I decided to get it out there now. There might be some issues with duplicate resource declarations on some role compinations as I have not tested all possible merges :). If this happens please open a separate issue for it and I'll fix it.

**Comment by stefanmortensen** [comment]
The new iteration of the installer currently in an early stage on the develop branch has an embryo for the template system. I'm going to close this issue as all further development will happen in the new installer.
