### ISSUE TITLE
Puppet breaks on Windows OS with German language

### ISSUE THREAD

**Issue by Smiliebg** [atomia/puppetmaster-gui#37]
It seems like there is an issue in Ruby/Facter which is causing the timezone you have set on the server to break Fact resolution which Puppet is not to happy about.

>> stderr: Fact resolution fact='timezone', resolution='' resolved to an invalid value: String "Mitteleurop\xE4ische Sommerzeit" doesn't match the reported encoding UTF-8

I've found several reports for this issue for example https://projects.puppetlabs.com/issues/13533 but unfortunately no resolution.

Until this is fixed, maybe to do pre-check of OS language and throw warning in GUI?

**Comment by stefanmortensen** [comment]
Implement as part of #41
