### ISSUE TITLE
InternalDNS is not working

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppetmaster-gui#40]
This file is always empty /etc/bind/pri/zone.conf - I mean it does not add records here.

This should be automatic? right?

**Comment by stefanmortensen** [comment]
Records should be added at the next puppet run on internal dns when a new server is added since it use exported resources to figure out what records to add.

Do the records appear if you run puppet again on internaldns while making sure you have at least 1 other server provisioned?

**Comment by stefanmortensen** [comment]
There where some issues related to the zone configuration now fixed with https://github.com/atomia/puppet-atomia/pull/133. I've verified that the records are being added, should you still have issues please reopen this issue.
