### ISSUE TITLE
InternalDNS ip_address field

### ISSUE THREAD

**Issue by stefanatomia** [atomia/puppetmaster-gui#46]
When installing internaldns server ip_address should be prefilled with ip of internal dns.
Or if this is not possible it should be mandatory field and not inside advanced configuration.
Any further provisioning of linux machines will fail because of /etc/resolv.conf
nameserver $ipaddress

**Comment by stefanmortensen** [comment]
It is automatically replaced please consider

https://github.com/atomia/puppet-atomia/blob/master/manifests/internaldns.pp#L15

$ip_address is by default the fact $ipaddress which is replaced by:

https://github.com/atomia/puppetmaster-gui/blob/3f09814af05a20a1e334f6940a90d124097f1569/app/public/js/atomia.js#L116-L121

Actual logic:

https://github.com/atomia/puppetmaster-gui/blob/194c49c3cd9c1d775e975a3aa615cd8f5c010d94/app/routes/servers.js#L37-L42

Make sure that
/servers/ip/hostname gives the ip address if not your hostname is not correctly resolving which is a pre requirement really.
