### ISSUE TITLE
ActionTrail IP is not making it's way to unattended

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppetmaster-gui#47]
Puppet does not put ip address of action trail in unattended.ini.

**Comment by stefanatomia** [comment]
Add mandatory field for this on this page /wizard/windows
actiontrail_ip

**Comment by stefanmortensen** [comment]
Would make more sense to add ip to internal_apps 

https://github.com/atomia/puppet-atomia/blob/2783256f6b12916ba25f9c96980f4cb9804b4705/manifests/internal_apps.pp#L13

If it is added with the default value $ipaddress it will be automatically expanded to the ip address of the server when added through the gui.

**Comment by stefanmortensen** [comment]
Fixed with https://github.com/atomia/puppet-atomia/pull/207
