### ISSUE TITLE
Atomia Internal Applications server wrong role

### ISSUE THREAD

**Issue by stefanatomia** [atomia/puppetmaster-gui#48]
After internal server finishes it will start again provisioning role atomia domain replica which is wrong.

**Comment by stefanmortensen** [comment]
I don't understand what you mean? Could you please explain some more. Do you mean that it automatically executes a provisioning run on the domain replica after internal applications is installed (similar to what it does with Nagios) or what?

**Comment by stefanatomia** [comment]
After joining to domain Internal server will contain fact atomia_role_1=active_directory_replica and continue with provisioning as AD replica. This happens in the middle of bootstrapping ( provisioning )

**Comment by stefanmortensen** [comment]
From what I can tell it is correctly getting the role internal_applications https://github.com/atomia/puppetmaster-gui/blob/22565b3c539d8b63a26de7e48da605611997cc90/app/routes/wizard.js#L94-L96

However If you reused the hostname it is possible that the database kept the "old" role. We do support having multiple roles on a single server now.

**Comment by stefanatomia** [comment]
No this was not with the reused hostname, and same thing happened at two different environments.

**Comment by stefanmortensen** [comment]
Fair enough, I will try to reproduce this

**Comment by stefanmortensen** [comment]
Harm Jan Stam Hi Stefan, I believe I've found a problem in the adjoin puppet class which is causing every windows server to be a active directory replica

[16:22]  
https://github.com/atomia/puppet-atomia/blob/master/manifests/adjoin.pp#L37-L39
 GitHub
atomia/puppet-atomia
puppet-atomia - Puppet module to install and configure Atomia 
 
 

[16:22]  
The adjoin class is included on every windows machine

[16:23]  
So on every windows machine the atomia_role_ad.ps1 is placed, so every windows server has the atomia_role_1=active_directory_replica fact

[16:24]  
Every server has now the AD DS role installed
