### ISSUE TITLE
Internal server doesn't get resource role ( lacking resources for automation server )

### ISSUE THREAD

**Issue by stefanatomia** [atomia/puppetmaster-gui#50]
For some reason Internal server doesn't have any transformation for resources, and i can see that we have resources role for doing creating those files.
It looks like role is not assigned to internal server...

**Comment by stefanmortensen** [comment]
It is assigned see https://github.com/atomia/puppet-atomia/blob/master/examples/hieradata/internal_apps.yaml#L6

For resource transformation to work you need the actual resources provisioned of course and then run provisioning on the internal_apps server. So what this means is that when the environment is fully installed a provisioning run on internal_apps should be done to create the resource transformations. This should be a postinstall step in #13

**Comment by stefanatomia** [comment]
Then please include this note in the installer, so that customers can actually know this is needed step.

**Comment by stefanmortensen** [comment]
see #13 :)
