### ISSUE TITLE
InternalDNS Hints

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppetmaster-gui#54]
allow_query filed:
Semi colon separated list of ip ranges allowed to query the dns server, if server is publically reachable this should be changed to contain your ip ranges

It should be added to this hint that at the end of the range there should be semicolon.
Smth like: "the expected value in this field is 173.254.0.0/24;"
Cause if user don't put semicolon at the end, neither will puppet which results in syntax error on internaldns.

Point: making hint more clearer and obvious.

**Comment by stefanmortensen** [comment]
Closing this because of #101
