### ISSUE TITLE
$ipaddress  in Advanced server configuration

### ISSUE THREAD

**Issue by zeljko-atomia** [atomia/puppetmaster-gui#59]
When checking the advanced configuration for the Internal DNS server, the ip_address field had value: **$ipaddress**. There is no mention if this is a placeholder or some variable, and if it is where does it get the value from.

![ipaddress](https://cloud.githubusercontent.com/assets/1143206/18128902/6fdc1d16-6f88-11e6-8579-9dd55fd523b6.PNG)

**Comment by stefanmortensen** [comment]
Happened again inhttps://github.com/atomia/puppet-atomia/issues/166

**Comment by stefanmortensen** [comment]
Closing this as the flow will be changed in the new installer and it is not super critical to implement in the old
