### ISSUE TITLE
On grouping roles make sure no conflict will arrise 

### ISSUE THREAD

**Issue by stefanmortensen** [atomia/puppetmaster-gui#63]
Installation wizard now supports multiple roles per server, please make sure that customer can not install conflicting roles per server;

for example, Internal DNS and Name Servers can not exist on same machine due to conflict on port 53.

Not sure if other conflicts may exists?

**Comment by jimmybergman** [comment]
I think we should have a whitelist of pairs that we know can coexist and block the installation of anything else is attempted (i.e. the other way, we keep a list of working combos, not of not-working).

And then we should expand the list as much as possible by testing and verifying that combos work.

**Comment by stefanmortensen** [comment]
Closing as this is being addressed in the new installer via environment templates
