### ISSUE TITLE
Missing icons on Dashbaord

### ISSUE THREAD

**Issue by zeljko-atomia** [atomia/puppetmaster-gui#78]
There are some icons missing on the dashboard:
mysq, postgres, haproxy at least 

![dashbboard-missing-icons](https://cloud.githubusercontent.com/assets/1143206/18586024/c59a5fe4-7c1a-11e6-96ef-b99f0b86d49d.PNG)

**Comment by stefanmortensen** [comment]
Closing this as the flow will be changed in the new installer and it is not super critical to implement in the old
