### ISSUE TITLE
Internaldns allow_query default value is mangled

### ISSUE THREAD

**Issue by zeljko-atomia** [atomia/puppetmaster-gui#98]
According to https://github.com/atomia/puppet-atomia/blob/aa847f2dada982232ada81c0a10c5f3f78be4fb3/manifests/internaldns.pp#L18 the allow_query value should be 
**any;**
but in puppetmaster-gui it shows as 
**any**

which then leads to machines not resolving internal DNS records, and halting the rest of the installation process.

**Comment by stefanmortensen** [comment]
internaldns role will be removed so this is now obsolete
